<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="../assets/xml/rss.xsl" media="all"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>The Cloistered Monkey (Posts about python errors)</title><link>https://necromuralist.github.io/</link><description></description><atom:link href="https://necromuralist.github.io/categories/python-errors.xml" rel="self" type="application/rss+xml"></atom:link><language>en</language><copyright>Contents © 2023 &lt;a href="mailto:cloisteredmonkey.jmark@slmail.me"&gt;Cloistered Monkey&lt;/a&gt; </copyright><lastBuildDate>Thu, 04 May 2023 00:33:49 GMT</lastBuildDate><generator>Nikola (getnikola.com)</generator><docs>http://blogs.law.harvard.edu/tech/rss</docs><item><title>Fatal Python Error</title><link>https://necromuralist.github.io/posts/fatal-platform-error/</link><dc:creator>Cloistered Monkey</dc:creator><description>&lt;p&gt;
I was going to make my first nikola post in a few months but when I tried the &lt;code&gt;nikola new_post&lt;/code&gt; command I got the following error.
&lt;/p&gt;

Traceback (most recent call last):
  File "/home/hades/.local/bin/pygmentize", line 5, in &lt;module&gt;
    from pygments.cmdline import main
ModuleNotFoundError: No module named 'pygments'

&lt;p&gt;
I had no idea what this meant so I tried searching the web for the error and found people saying different things about what it meant to them when they encountered it, but the one that pointed the way for me was a &lt;a href="https://github.com/pypa/virtualenv/issues/161"&gt;bug report for virtualenv&lt;/a&gt; where a user reported that he got this error because, it turned out, the Windows version didn't work with symlinks if the window was opened as an administrator.
&lt;/p&gt;

&lt;p&gt;
I'm not using Windows, but when I changed into the directory for my nikola virtualenv installation, &lt;code&gt;ls -l&lt;/code&gt; showed that all my symbolic links were broken. I don't know how it happened… maybe something got moved, but the point of this post was to make a note for myself if I see this error again - check the sym-links for the virtualenv installation.
&lt;/p&gt;&lt;/module&gt;</description><category>nikola</category><category>python errors</category><guid>https://necromuralist.github.io/posts/fatal-platform-error/</guid><pubDate>Sun, 19 Jun 2016 20:53:31 GMT</pubDate></item></channel></rss>